class len_Exception(Exception):
    def __init__(self):
        return None